// Code generated by Slice Machine. DO NOT EDIT.

import CtaBlock from './CtaBlock/index.svelte';
import BlogPostContent from './BlogPostContent/index.svelte';
import Image from './Image/index.svelte';
import IntroHeader from './IntroHeader/index.svelte';
import RichText from './RichText/index.svelte';
import SocialMedia from './SocialMedia/index.svelte';

export const components = {
	about_me: CtaBlock,
	blog_post_content: BlogPostContent,
	image: Image,
	intro_header: IntroHeader,
	rich_text: RichText,
	social_media: SocialMedia
};
