// Code generated by Slice Machine. DO NOT EDIT.

import BlogPostContent from './BlogPostContent/index.svelte';
import HomeHeader from './HomeHeader/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	blog_post_content: BlogPostContent,
	home_header: HomeHeader,
	rich_text: RichText
};
